### ISSUE TITLE
How to get the image data and image annotation?

### ISSUE THREAD

**Issue by Running-z** [IDR/idr-notebooks#67]
Hello, I am implementing your API code from your API page and getting only some JSON data, but shouldn't it be image data? If I want to use deep learning and train a classification model through your data, how can I use it? I don't get any image data and annotations. Is there a good tutorial or guidance?

**Comment by manics** [comment]
Hi, if you just need rendered images (e.g. JPEG, PNG) you can get those through the OMERO web API, but if you want the raw pixel values you'll need to use the [OMERO API](https://docs.openmicroscopy.org/omero/5.4.6/developers/index.html). It's best to use the [idr-py](https://github.com/IDR/idr-py/) library to connect since this allows load balancing of your connections which isn't supported by the standard OMERO API.

**Comment by manics** [comment]
Hi, if you just need rendered images (e.g. JPEG, PNG) you can get those through the [OMERO web API](https://docs.openmicroscopy.org/omero/5.4.6/developers/Web/WebGateway.html), no login is required for the IDR web API.

If you want the raw pixel values you'll need to use the [OMERO API](https://docs.openmicroscopy.org/omero/5.4.6/developers/index.html). It's best to use the [idr-py](https://github.com/IDR/idr-py/) library to connect since this allows load balancing of your connections which isn't supported by the standard OMERO API.
