### ISSUE TITLE
I don't know how to get the data and use it

### ISSUE THREAD

**Issue by zhouhao-learning** [IDR/idr-notebooks#68]
Hello, I want to download your data, but your API does not seem to provide me with downloads, I can only see the data, in addition, I want to use your data to train a deep learning model for classification, but your data should How to deal with it? Is there a good use case or guide?

**Comment by manics** [comment]
The easiest way to get started is to use our online Virtual Analysis Environment: https://idr-analysis.openmicroscopy.org/ The "Public access" option doesn't require a login, it's available to anyone and will give you a temporary session where you can explore the notebooks in a preconfigured environment.

If you just need rendered images (e.g. JPEG, PNG) you can get those through the [OMERO web API](https://docs.openmicroscopy.org/omero/5.4.6/developers/Web/WebGateway.html), no login is required for the IDR web API.

If you want the raw pixel values you'll need to use the [OMERO API](https://docs.openmicroscopy.org/omero/5.4.6/developers/index.html). It's best to use the [idr-py](https://github.com/IDR/idr-py/) library to connect since this allows load balancing of your connections which isn't supported by the standard OMERO API.
